### ISSUE TITLE
Why is there such a big gap between our results to your?

### ISSUE THREAD

**Issue by ZhuXiang-tuxing** [fdjingyuan/Deep-Fashion-Analysis-ECCV2018#6]
在相同的数据集下（DeepFashion/Category and Attribute Prediction Benchmark）,用同样的代码进行训练，但是我们这里的评估结果，和您发表的数据还是有较大的差异。

![image](https://user-images.githubusercontent.com/47967758/62346056-52433900-b527-11e9-842b-fa7bc1f9e016.png)

在关键点上差距在0.01~0.015，还是可以的，但是在属性检测上，前三大类的结果也可以接受，就是在Part, Style和All上，差距逐渐增大，从10到30，40。所以我想向您请教一下，为什么会存在这么大的差距，以及有什么方法可以增大召回率。如果有打扰到您了，在这里表示歉意！

**Comment by ousinkou** [comment]
请问找到问题原因没有？我的复现结果也差不多。Part与Style和论文差别太大
